print('Vamos criar uma história nada a ver com nada?')
print()
print("Para começar escreva 6 palavras nessa ordem:")
lugar = input("1) Digite um LUGAR: ")
famoso = input("2) Digite uma PESSOA FAMOSA: ")
objeto = input("3) Digite um OBJETO: ")
cor = input("4) Digite uma COR: ")
verbo = input("5) Digite um VERBO (ex: correr, dançar, gritar): ")
numero = input("6) Digite um NÚMERO: ")
print()
print("🔮Pronto! Aqui vai:")
print()
print(f"📍 Era uma vez em {lugar}, onde tudo era {cor} e meio suspeito...")
print(f"De repente, {famoso} apareceu segurando um(a) {objeto} e gritou:")
print(f"Hoje eu vou {verbo} {numero} vezes sem parar!!! 😱")
print(f"Todo mundo em {lugar} ficou em choque 🤯 e começou a aplaudir 👏👏👏")
print("E assim nasceu a lenda mais estranha do universo. FIM.")